fleet:
robot:
category: delivery # request category
description:
  pickup:
    place: office
    handler: lounge_dispenser
    payload:
      sku: coke
      quantity: 1
  dropoff:
    place: office
    handler: office_ingestor
    payload:
      sku: coke
      quantity: 1
